{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "lunch-money-k8s.fullname" . }}
  labels:
    {{- include "lunch-money-k8s.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "lunch-money-k8s.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:  # http port, reachable from anywhere in the cluster
        - protocol: TCP
          port: 8080
  egress:
    - ports:  # DNS resolution
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:  # HTTPS out to the Lunch Money API and AWS SSM
        - protocol: TCP
          port: 443
{{- end }}
