{{- if not .Values.lunchMoney.existingSecret }}
{{- if not .Values.lunchMoney.token }}
{{- fail "Set lunchMoney.token or lunchMoney.existingSecret" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lunch-money-k8s.fullname" . }}
  labels:
    {{- include "lunch-money-k8s.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  token: {{ .Values.lunchMoney.token | quote }}
{{- end }}
