apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunch-money-k8s.fullname" . }}
  labels:
    {{- include "lunch-money-k8s.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lunch-money-k8s.selectorLabels" . | nindent 4 }}
